### ISSUE TITLE
jforum3

### ISSUE THREAD

**Issue by saravanamurali** [rafaelsteil/jforum3#20]
I have downloded jforum3 and installed which is not showing list of created fourms. And finally I fixed the issue. But now which is showing the error on  posting to my forums and replying to my forums. Can you please reply to my post.

**Comment by vitalijzad** [comment]
From the README:

> Right now project is in terrible condition. Do not use it on you site. It's not ready.

**Comment by ooooooobh** [comment]
who  finish this jforum3，and build it without error。I  want  get  the  successful  codes;
who can help me. ths;

**Comment by liudianpeng** [comment]
log4j:WARN No appenders could be found for logger (com.mchange.v2.log.MLog).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
12-Jul-2017 11:59:37.001 信息 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [C:\_____Soft______\apache-tomcat-9.0.0.M22\webapps\manager]
12-Jul-2017 11:59:37.161 信息 [ContainerBackgroundProcessor[StandardEngine[Catalina]]] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [C:\_____Soft______\apache-tomcat-9.0.0.M22\webapps\manager] has finished in [161] ms
12:00:03,364  WARN [SettingsFactory     ] Could not obtain connection metadata
java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:529)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
	at org.hibernate.connection.C3P0ConnectionProvider.getConnection(C3P0ConnectionProvider.java:56)
	at org.hibernate.cfg.SettingsFactory.buildSettings(SettingsFactory.java:84)
	at org.hibernate.cfg.Configuration.buildSettings(Configuration.java:2073)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1298)
	at org.hibernate.cfg.AnnotationConfiguration.buildSessionFactory(AnnotationConfiguration.java:859)
	at net.jforum.core.support.hibernate.SessionFactoryCreator.create(SessionFactoryCreator.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:340)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:293)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:130)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:394)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1413)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:263)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1083)
	at br.com.caelum.vraptor.ioc.spring.SpringBasedContainer.instanceFor(SpringBasedContainer.java:86)
	at br.com.caelum.vraptor.ioc.spring.ComponentFactoryBean.getObject(ComponentFactoryBean.java:43)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:142)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:109)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1429)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:245)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:844)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:786)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:703)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:795)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:723)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:196)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1003)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:907)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:844)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:786)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:703)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:795)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:723)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:196)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1003)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:907)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:485)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:580)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
	at br.com.caelum.vraptor.ioc.spring.SpringBasedContainer.start(SpringBasedContainer.java:106)
	at br.com.caelum.vraptor.ioc.spring.SpringProvider.start(SpringProvider.java:87)
	at br.com.caelum.vraptor.VRaptor.init(VRaptor.java:110)
	at br.com.caelum.vraptor.VRaptor.init(VRaptor.java:103)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:283)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:264)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:108)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4481)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5121)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:740)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:716)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1729)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(Unknown Source)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:456)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:405)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at sun.rmi.transport.Transport$1.run(Unknown Source)
	at sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$254(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$$Lambda$17/403136539.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1319)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
	... 115 more
12:00:03,432  INFO [Dialect             ] Using dialect: org.hibernate.dialect.MySQL5InnoDBDialect
12:00:03,438  INFO [TransactionFactoryFactory] Using default transaction strategy (direct JDBC transactions)
12:00:03,453  INFO [TransactionManagerLookupFactory] No TransactionManagerLookup configured (in JTA environment, use of read-write or transactional second-level cache is not recommended)
12:00:03,453  INFO [SettingsFactory     ] Automatic flush during beforeCompletion(): disabled
12:00:03,453  INFO [SettingsFactory     ] Automatic session close at end of transaction: disabled
12:00:03,454  INFO [SettingsFactory     ] Scrollable result sets: disabled
12:00:03,454  INFO [SettingsFactory     ] JDBC3 getGeneratedKeys(): disabled
12:00:03,454  INFO [SettingsFactory     ] Connection release mode: auto
12:00:03,457  INFO [SettingsFactory     ] Maximum outer join fetch depth: 2
12:00:03,458  INFO [SettingsFactory     ] Default batch fetch size: 1
12:00:03,458  INFO [SettingsFactory     ] Generate SQL with comments: disabled
12:00:03,458  INFO [SettingsFactory     ] Order SQL updates by primary key: disabled
12:00:03,458  INFO [SettingsFactory     ] Order SQL inserts for batching: disabled
12:00:03,458  INFO [SettingsFactory     ] Query translator: org.hibernate.hql.ast.ASTQueryTranslatorFactory
12:00:03,464  INFO [ASTQueryTranslatorFactory] Using ASTQueryTranslatorFactory
12:00:03,465  INFO [SettingsFactory     ] Query language substitutions: {}
12:00:03,465  INFO [SettingsFactory     ] JPA-QL strict compliance: disabled
12:00:03,465  INFO [SettingsFactory     ] Second-level cache: disabled
12:00:03,465  INFO [SettingsFactory     ] Query cache: disabled
12:00:03,465  INFO [SettingsFactory     ] Optimize cache for minimal puts: disabled
12:00:03,465  INFO [SettingsFactory     ] Structured second-level cache entries: enabled
12:00:03,477  INFO [SettingsFactory     ] Echoing all SQL to stdout
12:00:03,477  INFO [SettingsFactory     ] Statistics: disabled
12:00:03,478  INFO [SettingsFactory     ] Deleted entity synthetic identifier rollback: disabled
12:00:03,479  INFO [SettingsFactory     ] Default entity-mode: pojo
12:00:03,480  INFO [SettingsFactory     ] Named query checking : enabled
12:00:03,516  INFO [SessionFactoryImpl  ] building session factory
12:00:03,983  INFO [SessionFactoryObjectFactory] Not binding factory to JNDI, no JNDI name configured
12:00:04,050  INFO [DefaultListableBeanFactory] Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@583ea290: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,defaultRouter,XStreamConverters.NullConverter,defaultMethodNotAllowedHandler,pathAnnotationRoutesParser,topologicalSortedInterceptorRegistry,defaultMultipartConfig,defaultConverters,noRoutesConfiguration,defaultDeserializers,defaultRestDefaults,defaultTypeNameExtractor,defaultTypeFinder,javaEvaluator,defaultAcceptHeaderToFormat,interceptorListPriorToExecutionExtractor,defaultInterceptorHandlerFactory,cglibProxifier,paranamerNameProvider,defaultResourceNotFoundHandler,defaultResourceTranslator,objenesisInstanceCreator,defaultRoutes,encodingHandlerFactory,hibernateProxyInitializer,stereotypeHandler,converterHandler,interceptorStereotypeHandler,deserializesHandler,stereotypedBeansRegistrar,defaultSpringLocator,defaultMethodInfo,instantiateInterceptor,defaultRepresentationResult,downloadInterceptor,emptyResult,defaultPathResolver,flashInterceptor,defaultLogicResult,commonsUploadMultipartInterceptor,sessionFlashScope,forwardToDefaultViewInterceptor,nullBeanValidator,deserializingInterceptor,parametersInstantiatorInterceptor,defaultValidator,defaultExceptionMapper,outjectResult,defaultPageResult,applicationConfiguration,defaultRefererResult,XStreamJSONSerialization,defaultFormatResolver,defaultResult,exceptionHandlerInterceptor,messageConverter,defaultServletFileUploadCreator,HTMLSerialization,jsonDeserializer,defaultHttpResult,defaultValidationViewsFactory,executeMethodInterceptor,XStreamJSONPSerialization,XStreamXMLSerialization,XStreamConverters,ognlFacade,XStreamXMLDeserializer,jstlLocalization,defaultRestHeadersHandler,replicatorOutjector,resourceLookupInterceptor,defaultStatus,ognlParametersProvider,emptyElementsRemoval,shortConverter,primitiveDoubleConverter,uploadedFileConverter,localeBasedCalendarConverter,primitiveBooleanConverter,primitiveFloatConverter,enumConverter,primitiveCharConverter,doubleConverter,primitiveLongConverter,integerConverter,booleanConverter,stringConverter,bigDecimalConverter,byteConverter,primitiveByteConverter,primitiveShortConverter,characterConverter,floatConverter,longConverter,bigIntegerConverter,localeBasedDateConverter,primitiveIntConverter,VRaptorRequestProvider,httpServletRequestProvider,httpServletResponseProvider,httpSessionProvider,defaultInterceptorStack,XStreamBuilderImpl,enhancedRequestExecution,org.springframework.aop.config.internalAutoProxyCreator,userSession,newLineToHtmlBreakFormatter,postController,avatarService,i18n,category,authenticatedRule,adminController,pollVoter,downloadAttachmentRule,sessionManagerInterceptor,recentTopicsController,badWord,configController,recentTopicsRepository,privateMessageController,moderationService,BBConfigFormatter,mostUsersEverOnlineService,moderationLogRepository,postReportRepository,sessionCreator,RSSRepository,role,categoryAdminController,forumService,RSSService,lostPasswordService,attachmentRepository,postEditInterceptor,safeHtml,topic,forumRepository,userService,topicService,postService,topicWatchExtension,postReport,poll,themeRepository,topicController,moderationRule,groupAdminController,attachment,categoryRepository,privateMessage,messageController,banlistRepository,avatar,searchRepository,VRaptorCustomPathResolver,accessForumRule,attachmentQuota,rankingRepository,searchController,forumController,luceneAdminController,htmlEntitiesFormatter,ranking,themeController,attachmentService,smilieRepository,hibernateTransactionInterceptor,groupInteractionFilter,userRepository,avatarRepository,session,badWordRepository,postRepository,topicWatchRepository,forumAdminController,pollService,JForumConfig,forumLimitedTimeRepository,defaultLoginAuthenticator,smiliesFormatter,config,smilieAdminController,methodSecurityInterceptor,pollOption,createNewTopicRule,rankingAdminController,safeHtmlTagsFormatter,safeHtmlAttributesFormatter,userAdminController,avatarAdminController,post,userController,pollRepository,privateMessageEnabledRule,theme,postReportController,hibernateStatisticsController,banlist,postFormatters,changePostRule,privateMessageService,categoryService,privateMessageRepository,forumWatch,user,topicWatchService,RSSController,moderationLogService,configService,sessionRepository,topicWatch,badWordAdminController,postReportCounterOperation,rankingService,privateMessageOwnerRule,moderationLog,controllerSecurityInterceptor,smilieService,groupService,sessionFactoryCreator,topicRepository,smilie,moderationController,groupRepository,configRepository,forum,group,attachmentExtension,replyTopicRule,sessionManager,editUserRule,banlistAdminController,administrationRule]; root of factory hierarchy
12:00:04,053  INFO [SessionFactoryImpl  ] closing
12-Jul-2017 12:00:04.055 严重 [RMI TCP Connection(3)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
12-Jul-2017 12:00:04.055 严重 [RMI TCP Connection(3)-127.0.0.1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
12-Jul-2017 12:00:04.064 警告 [RMI TCP Connection(3)-127.0.0.1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
[2017-07-12 12:00:04,077] Artifact jforum3:war exploded: Error during artifact deployment. See server log for details.

**Comment by liudianpeng** [comment]
Why can't I connect to the database?

**Comment by ryantheleach** [comment]
> Disclaimer: I am not actively working on the code anymore, as I moved to another projects and priorities over the years. I keep it here for historical reasons and because it may be useful to someone. This v3 was intented to be a next gen of v2, a total rewrite with new features and approaches. However, interest on the project dismissed over time, and I saw no reason to keep working on it.
